using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Mimsv2.Models;

namespace Mimsv2.Services
{
    public class GroupQualityIndicatorsPdfService
    {
        public byte[] Generate(List<GroupQualityIndicatorModel> data)
        {
            var grouped = data.GroupBy(x => x.Hospital).ToList();

            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(30);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(10));

                    page.Header().Row(row =>
                    {
                        row.RelativeItem().Column(col =>
                        {
                            col.Item().Text("Group Quality Indicators").Bold().FontSize(16);
                            col.Item().Text($"Generated: {DateTime.Now:yyyy-MM-dd}").FontSize(10).FontColor(Colors.Grey.Darken1);
                        });

                        //row.ConstantItem(60).Image("wwwroot/images/mimsv2.png", ImageScaling.FitArea); // Adjust path & size
                    });

                    page.Content().PaddingVertical(10).Column(col =>
                    {
                        foreach (var group in grouped)
                        {
                            col.Item().PaddingBottom(20).Column(hospitalSection =>
                            {
                                hospitalSection.Item().Text(group.Key).Bold().FontSize(14).FontColor(Colors.Blue.Medium);
                                hospitalSection.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                                hospitalSection.Item().Table(table =>
                                {
                                    table.ColumnsDefinition(columns =>
                                    {
                                        columns.ConstantColumn(30); // #
                                        columns.RelativeColumn(2); // Summary
                                        columns.ConstantColumn(60); // Severity
                                        columns.RelativeColumn(1); // Department
                                        columns.RelativeColumn(2); // Corrective Actions
                                    });

                                    table.Header(header =>
                                    {
                                        header.Cell().Text("#").Bold();
                                        header.Cell().Text("Incident Category & Description").Bold();
                                        header.Cell().Text("Severity").Bold();
                                        header.Cell().Text("Department").Bold();
                                        header.Cell().Text("Corrective Actions").Bold();
                                    });

                                    int i = 1;
                                    foreach (var item in group)
                                    {
                                        table.Cell().Text(i++.ToString());
                                        table.Cell().Text(item.Summary);
                                        table.Cell().Text(item.Severity);
                                        table.Cell().Text(item.Department);
                                        table.Cell().Text(item.CorrectiveActions);
                                    }
                                });
                            });

                            col.Item().PageBreak();
                        }
                    });

                    page.Footer().AlignCenter().Text(txt =>
                    {
                        txt.Span("Confidential · ");
                        txt.Span("Generated by MIMS Quality System").FontSize(9).FontColor(Colors.Grey.Darken2);
                    });
                });
            });

            return document.GeneratePdf();
        }
    }
}
